### ISSUE TITLE
[Bug] Uncaught Runtime error 

### ISSUE THREAD

**Issue by Rashmi-278** [creativetimofficial/notus-nextjs#6]
### Version
next@10.1
### Reproduction link
https://demos.creative-tim.com/notus-nextjs?_ga=2.261760520.424340754.1610867537-881030562.1610431277
### Operating System
Linux mint
### Device
DELL PRECISION T5500
### Browser & Version
Version 86.0.4240.75 (Official Build) (64-bit) Google chrome
### Steps to reproduce
npm run dev , 
inspect element to view responsive index page
reload the mobile responsive page 

nextjs throws you a uncaught runtime error
### What is expected?
No runtime error 
### What is actually happening?
Unhandled Runtime Error
ChunkLoadError: Loading chunk 0 failed.
(error: http://localhost:3000/_next/static/chunks/0.js)
Source
../../client/next-dev.js (16:0) @ Object.eval

  14 | // The runtimeChunk can't hot reload itself currently to correct it when adding pages using on-demand-entries
  15 | // eslint-disable-next-line no-unused-expressions
> 16 | __REPLACE_NOOP_IMPORT__
  17 | 
  18 | // Support EventSource on Internet Explorer 11
  19 | if (!window.EventSource) {

Call Stack
eval
webpack-internal:///./node_modules/next/dist/client/next-dev.js (155:30)
Object../node_modules/next/dist/client/next-dev.js
file:///home/torch/Desktop/Fresh/notuspub/.next/static/chunks/main.js (737:1)
__webpack_require__
/_next/static/chunks/webpack.js (873:31)
checkDeferredModules
file:///home/torch/Desktop/Fresh/notuspub/.next/static/chunks/webpack.js (46:23)
webpackJsonpCallback
/_next/static/chunks/webpack.js (33:19)
<unknown>
file:///home/torch/Desktop/Fresh/notuspub/.next/static/chunks/webpack.js (1015:54)
<unknown>
/_next/static/chunks/webpack.js (1023:10)

---

**Comment by EINazare** [comment]
Please make a video with the following:

* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

Best,
Manu
