### ISSUE TITLE
[Bug] npm install fails

### ISSUE THREAD

**Issue by brilang** [creativetimofficial/notus-nextjs#8]
### Version
1.00
### Reproduction link
https://github.com/brilang/fvcb4
### Operating System
Windows 10 Home 64-bit
### Device
Dell Gaming PC, Intel i7-10700F, 32GB memory
### Browser & Version
n/a
### Steps to reproduce
1. Download notus-nextjs-master.zip from the Notus NextJS page
2. Extract to directory (in my case, C:\Users\brila\Projects\fvcb4)
3. Run npm install in project directory
4. Read error messages

### What is expected?
npm install should succeed
### What is actually happening?
Errors are being generated

---
### Additional comments
Contents of eresolve-report.txt follows:

# npm resolution error report

2021-03-03T02:31:19.430Z

Found: typescript@4.0.3
node_modules/typescript
  optional typescript@"4.0.3" from the root project

Could not resolve dependency:
peerOptional typescript@"^3.2.1" from react-scripts@3.4.3
node_modules/react-scripts
  react-scripts@"3.4.3" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "typescript",
    "version": "4.0.3",
    "location": "node_modules/typescript",
    "dependents": [
      {
        "type": "optional",
        "name": "typescript",
        "spec": "4.0.3",
        "from": {
          "location": "C:\\Users\\brila\\Projects\\fvcb4"
        }
      }
    ]
  },
  "edge": {
    "type": "peerOptional",
    "name": "typescript",
    "spec": "^3.2.1",
    "error": "INVALID",
    "from": {
      "name": "react-scripts",
      "version": "3.4.3",
      "location": "node_modules/react-scripts",
      "dependents": [
        {
          "type": "prod",
          "name": "react-scripts",
          "spec": "3.4.3",
          "from": {
            "location": "C:\\Users\\brila\\Projects\\fvcb4"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}

**Comment by EINazare** [comment]
Hello there, @brilang ,

Thank you for your interest in working with our products.
On our machines, everything is working as expected. Maybe your issue arises from the NodeJS version that you are using.
Please download and install NodeJS LTS version 14.16.0: https://nodejs.org/en/
If that does not solve your issue, please provide us the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

Best,
Manu

**Comment by brilang** [comment]
I have done those steps exactly, but my Node version is 15.10.0 and my npm version is 7.6.0

![image](https://user-images.githubusercontent.com/867983/109913576-1b815780-7c63-11eb-9bcd-5c80fcb28935.png)

Contents of eresolve-report.txt were pasted yesterday.

**Comment by EINazare** [comment]
Hello there, @brilang ,

Please download and install NodeJS LTS version 14.16.0: https://nodejs.org/en/
After that, download the product again and start fresh.

Best,
Manu

**Comment by brilang** [comment]
I have now tried on my work PC.
OS: Windows 10 Pro 20H2
Device: HP EliteDesk i7-4770
I get the same error.

![image](https://user-images.githubusercontent.com/867983/110986694-d627ee80-8322-11eb-88b2-6816f417dd03.png)

**Comment by EINazare** [comment]
Hello again, @brilang ,

I've tested the product 10 times now, and it works as expected.
Please provide the following video:
Download the product
- Unzip the product
- Open terminal and cd into the project
- Run node -v
- Run npm -v
- [Mac/Ubuntu/Linux] Run npm run install:clean
- [Widnows] Run npm install
- [Widnows] Run npm start
- Showcase the issue

Best,
Manu

**Comment by brilang** [comment]
Issue #10 fixed this for me.
